ckpt_path: null
codec_name: hificodec
dataloader:
  batch_size: 64
  num_workers: 4
dataset:
  codec: hificodec
  dataset_path: /project2/shrikann_35/DATA/Vox1/codec_feats/
  emotion_model: wavlm
dataset_name: vox1
dataset_sr: 16000
gpus: '0'
input_type: quantized_embedding
lightning:
  adv_annealing_steps: 50000
  adv_loss_weight: 0.25
  adv_update_factor: 5
  adv_weight_decay: 0.001
  ae_warmup_steps: 50000
  codec_dim: 512
  dec_channels:
  - 256
  enc_channels:
  - 256
  - 128
  gradient_clip_val: 100.0
  latent_dim: 64
  learning_rate: 0.001
  log_gradients: true
  lr_scheduling: false
  normalize_input: true
  use_adversarial: true
  weight_decay: 0
random_seed: 42
tensorboard:
  name: repro-4
  save_dir: /project2/shrikann_35/nmehlman/logs/private_codecs/tensorboard/gender
  version: null
trainer:
  accelerator: gpu
  detect_anomaly: false
  deterministic: false
  devices: auto
  log_every_n_steps: 10
  max_epochs: 250
  sync_batchnorm: true
  val_check_interval: 1.0
  
