random_seed: 42
dataset_name: "vox1"
codec_name: "hificodec"
input_type: "quantized_embedding"
device: "cpu" # DEBUG
gpus: "0"

log_dir: "/project2/shrikann_35/nmehlman/logs/private_codecs/tensorboard/gender/longer/version_3"
ckpt_name: null
num_samples_to_save: 10
cache_dir: "/project2/shrikann_35/nmehlman/logs/private_codecs/audio_eval_cache/"
num_cached_samples: 1000


# Dataset options:
dataset:
  train_val_spks_split_file: "/project2/shrikann_35/nmehlman/data/svpp-data/vox1/priv_codec_train_val_skp.json"
  data_dir: "/project2/shrikann_35/nmehlman/data/svpp-data/vox1/" 
  audio_subdir: "vox1_dev_wav"
